package org.drools.workshop.cep

import java.util.List;
import org.drools.workshop.cepmodel.BlackListedClient;
import org.drools.workshop.cepmodel.Client;
import org.drools.workshop.cepmodel.FraudSuspicion;
import org.drools.workshop.cepmodel.Transaction;

declare Transcaction
  @role ( event )
  @timestamp ( transactionTime )
  @expires ( 30m )
end

rule "too many transactions from same client in last half hour"
  when
    Transaction($cname: client.name)
    $list: List(size > 10) from collect(
        Transcaction(client.name == $cname) over window:time(30m)
    )
  then
    insertLogical(new FraudSuspicion($c, $list));
end

rule "Audit suspicious cases from blacklisted clients"
  when
    $fraudSuspicion: FraudSuspicion($cname: client.name)
    BlackListedClient(client.name == $cname)
  then
    channels["auditing"].send($fraudSuspicion);
end
