package org.drools.workshop;

import org.drools.workshop.model.*;
import org.drools.workshop.model.Person.*;
import java.util.List;

rule "room and a person"
    when
        $r: Room()
        $p: Person()
    then
        System.out.println(">>> There is a Room: "+ $r);
        System.out.println(">>> And There is a Person: "+ $p);
end

rule "overcrowded room"
    when
        $r: Room()
         List($amount: size > $r.getCapacity()) from collect (Person() from $r.getPersons())
    then
        System.out.println(">>> The room is over crowded by "+ ($amount - $r.getCapacity())  +" people");
end