package org.drools.workshop;

import org.drools.workshop.model.*;
import org.drools.workshop.model.Person.*;
import java.util.List;

rule "room and a person"
    when
        $r: Room()
        $p: Person()
    then
        System.out.println("There is a Room: "+ $r);
        System.out.println("And There is a Person: "+ $p);
end



rule "room from a house"
    when
        $r: Room()
        $h: House(rooms != null , rooms.contains($r))
    then
        System.out.println("There is a Room: "+ $r);
        System.out.println("And There is a House: "+ $h);
end